# Generated by Django 5.2.9 on 2025-12-03 09:21

import django.db.models.deletion
import requests_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('DRAFT', 'Не подписан'), ('ACTIVE', 'Подписан'), ('CANCELLED', 'Расторгнут')], default='DRAFT', max_length=16, verbose_name='Статус')),
                ('priority', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=3, verbose_name='Приоритет')),
                ('file', models.FileField(blank=True, null=True, upload_to=requests_manager.models.file_upload_path, verbose_name='Файлы заявки')),
                ('start_date', models.DateField(verbose_name='Дата вступления в силу')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата расторжения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Номер заявки')),
                ('content', models.CharField(max_length=256, verbose_name='Комментарий')),
                ('start_date', models.DateField(verbose_name='Дата вступления в силу')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата расторжения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_comments', to='requests_manager.request', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коментарий к заявке',
                'verbose_name_plural': 'Коментарии к заявке',
                'db_table': 'request_comments',
            },
        ),
    ]
