# Generated by Django 5.2.9 on 2025-12-03 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата вступления в силу'),
        ),
    ]
