# Generated by Django 5.2.9 on 2025-12-03 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_manager', '0002_alter_request_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файлы заявки'),
        ),
        migrations.AlterField(
            model_name='requestcomment',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата вступления в силу'),
        ),
    ]
