# Generated by Django 5.2.9 on 2025-12-05 07:08

import requests_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_manager', '0003_alter_request_file_alter_requestcomment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=requests_manager.models.file_upload_path, verbose_name='Файлы заявки'),
        ),
    ]
