# Generated by Django 5.2.9 on 2025-12-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
