# Generated by Django 5.2.9 on 2025-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
    ]
